/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dairymanagementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.regex.*;
/**
 *
 * @author Akhil
 */
public class ManagerSignupUI extends javax.swing.JFrame {

    Connection connection = null;
    /**
     * Creates new form LoginUI
     */
    public ManagerSignupUI() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }
    

    
//****************************  To add manager to table ***************************
 
    private void addManagerToTable(String name, String email, String pass){
        
        String url = " insert into manager(mg_name,mg_email,mg_password) values('"+name+"','"+email+"','"+pass+"');";
        
        try{
            connection = ConnectionManager.getConnection();
            
            PreparedStatement ps = connection.prepareStatement(url);
            
            int i = ps.executeUpdate();
            
            if( i> 0){
                JOptionPane.showConfirmDialog(this, "Saved Successfully ?");
           }
        }
        catch( Exception ex){
            System.out.println("Error in dairymanagementsystem.ManagerSignupUI.addManagerToTable(): " + ex.getMessage());
        }
    }
   
//    Checking data before adding to manager table. if they aare null or not
   private int checkManagerSignupField(){
       String pass1 = String.valueOf(managerNewjPasswordField.getPassword());
       String pass2 = String.valueOf(managerConfirmjPasswordField.getPassword());
       if( managerNamejTextField.getText().isEmpty() || managerEmailjTextField.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Name OR Email not valid!!");
           return 0;
       }
       if( pass1.equals("")  || pass1 == null){
           JOptionPane.showMessageDialog(this, "Password not valid!!");
           return 0;
       }
       else {
           if ( !pass1.equals(pass2)){
               JOptionPane.showMessageDialog(this, "Password not match");
               return 0;
           }
           return 1;
       }
       
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        managerEmailjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        managerNewjPasswordField = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        managerNamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        managerConfirmjPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(651, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 22)); // NOI18N
        jLabel1.setText("Dairy Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(220, 254, 251));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Manager Sign UP Form");

        jLabel3.setText("Email");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dairymanagementsystem/Annotation 2022-03-25 221043.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        managerEmailjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                managerEmailjTextFieldFocusLost(evt);
            }
        });
        managerEmailjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                managerEmailjTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setText("New Password");

        managerNewjPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerNewjPasswordFieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Sign UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        managerNamejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                managerNamejTextFieldFocusLost(evt);
            }
        });
        managerNamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                managerNamejTextFieldKeyReleased(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("Confirm Password");

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(managerConfirmjPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(managerEmailjTextField)
                                    .addComponent(managerNewjPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(managerNamejTextField)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(124, 124, 124)
                                .addComponent(jButton1)))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(managerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(managerEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(managerNewjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(managerConfirmjPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        int i = checkManagerSignupField();
        
        if( i == 1){
            String name = managerNamejTextField.getText();
            String email = managerEmailjTextField.getText();
            String pass1 = String.valueOf(managerNewjPasswordField.getPassword());
            String pass2 = String.valueOf(managerConfirmjPasswordField.getPassword());
            
            if( name.isEmpty() || email.isEmpty() || pass1.isEmpty() || pass2.isEmpty()){
                JOptionPane.showMessageDialog(this, "Empty fields are not allowed");
            }
            else{
                
                addManagerToTable(name, email, pass1);
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ManagerLoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void managerNewjPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerNewjPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerNewjPasswordFieldActionPerformed

    private void managerNamejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_managerNamejTextFieldKeyReleased
        // TODO add your handling code here:
//        String PATTERN = "^[a-zA-Z]{3,20}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(managerNamejTextField.getText());
//        
//        if(!match.matches()){
//            jLabel5.setText("Naming is incorrect");
//            
//        }
//        else{
//            jLabel5.setText(null);
//        }
        
    }//GEN-LAST:event_managerNamejTextFieldKeyReleased

    private void managerEmailjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_managerEmailjTextFieldKeyReleased
        // TODO add your handling code here:
//           String PATTERN = "^[a-zA-Z0-9]{3,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(managerEmailjTextField.getText());
//        
//        if(!match.matches()){
//            jLabel5.setText("Email is incorrect");
//            
//        }
//        else{
//            jLabel5.setText(null);
//        }
    }//GEN-LAST:event_managerEmailjTextFieldKeyReleased

    private void managerNamejTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_managerNamejTextFieldFocusLost
        // TODO add your handling code here:
           String PATTERN = "^[a-zA-Z]{3,18}";
        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(managerNamejTextField.getText());
        String name = managerNamejTextField.getText();

        if(! patt.matcher(name).matches()){
            JOptionPane.showMessageDialog(this, "Incorrect Name");
            jLabel5.setText("Naming is incorrect");
            managerNamejTextField.setText("");
        }
        else{
            jLabel5.setText(null);
        }
    }//GEN-LAST:event_managerNamejTextFieldFocusLost

    private void managerEmailjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_managerEmailjTextFieldFocusLost
        // TODO add your handling code here:
            String PATTERN = "^[a-zA-Z0-9]{3,25}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}";
        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match = patt.matcher(managerNamejTextField.getText());
        String name = managerEmailjTextField.getText();

        if(! patt.matcher(name).matches()){
//            JOptionPane.showMessageDialog(this, "Incorrect Email");
            jLabel5.setText("Email is incorrect");
            managerEmailjTextField.setText("");
        }
        else{
            jLabel5.setText(null);
        }
    }//GEN-LAST:event_managerEmailjTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerSignupUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField managerConfirmjPasswordField;
    private javax.swing.JTextField managerEmailjTextField;
    private javax.swing.JTextField managerNamejTextField;
    private javax.swing.JPasswordField managerNewjPasswordField;
    // End of variables declaration//GEN-END:variables
}
